module.exports = () => ({
    "address": null,
    "ailmentsTreated": [],
    "averageRating": null,
    "city":null,
    "country": null,
    "designation": null,
    "education": [],
    "email": null,
    "experience": [],
    "firstName": null,
    "gender": null,
    "hospital": {},
    "isPersonAllowed": null,
    "isVideoAllowed": null,
    "landmark": null,
    "languages": null,
    "lastName": null,
    "licenses": {},
    "locality": null,
    "location": null,
    "name": null,
    "phone": null,
    "schedule":{},
    "specialization":null,
    "state":null,
    "yearsOfExperience":null
})